#!/bin/bash

echo "Now creating the Vehicle Database: "
echo
echo

sqlite3 vehicle.db <<EOF
CREATE TABLE Vehicle (
    ID INTEGER PRIMARY KEY,
    Type VARCHAR(10),
    Make VARCHAR(25),
    Model VARCHAR(25),
    Year INTEGER,
    Mileage INTEGER,
    VIN VARCHAR(17),
    License_Plate VARCHAR(7)
);


EOF

chmod +x cpdatabase
chmod +x adddb
chmod +x sortdb.pl
